name: CI pertama saya

on: push

jobs:
  halo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/code
        uses: actions/checkout@v4

      - name: Cetak Pesan
        run: docker build -t halo-image .
