name: CI pertama saya

on: push

jobs:
  halo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/code
        uses: actions/checkout@v4

      - name: login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: cetak pesan
        run: docker build -t dewadevops/halo-image .

      - name: ngepush ke docker
        run: docker push  dewadevops/halo-image

      - name: Pesan Rahasia
        run: echo "pesan rahasianya adalah ${{ secrets.PESAN_RAHASIA }}"
